### ISSUE TITLE
Add controller support and per game proton option.

### ISSUE THREAD

**Issue by isilkin** [Gr3gorywolf/batocera_wine_manager#1]
I think this is more of a feature request. I think the app is amazing. I know someone else is working on allowing custom runners for the future batocera versions too. 
1. If you leave install dependencies switch on then no game will launch it will just try to install dependencies and exit. So you have to toggle the switch to off position in order to run the game.
2. It would be nice to have controller support to toggle the switches on and off as well as download proton versions using a controller.
3. How can I verify that the windows game is using a custom proton version instead of the built in wine. Also how can I tell if the dependencies have indeed installed for a specific prefix?
4. Is there a way to run different proton versions for different games.
Thank you and very good work.

**Comment by Gr3gorywolf** [comment]
1. The dependencies installation is basically a launch mode, if its enabled no game will run, instead it will install all the needed dependencies, on the game prefix so In order to disable that mode you should disable the dependencies install
2. yes, I have that planned, because I use a pair of dragonrise joysticks and I would love to use my arcade machine's native controls instead of a mouse/keyboard
3. Its really tricky to determine that, you should launch a windows game without the autorun.cmd, once in the explorer execute windows/system32/winecfg.exe and go to the about tab, and it tells you the wine version like this: 
![image](https://github.com/Gr3gorywolf/batocera_wine_manager/assets/26353631/2ad9664e-9782-4382-8f89-98a8f79abfac)
4. Unfortunetly no, it just overrides the batocera's default wine, so there's no way to work around it

also I have a question for you. How do you feel the app interface, is it clear enough?

**Comment by isilkin** [comment]
Yes, the interface was super easy. but if I may critique it a bit to make it better.
See screenshot below of the GUI if you are offline.

1.If you are offline and using custom proton the GUI should tell you that you are currently using this version of proton. Instead it just tells you to use batocera's wine default. 
2. The difference between 2 toggle switches for redistributables is not clear. It seems if I toggle the second one it will do everything for me.
3. Lastly I installed a few games and Everytime I installed a game I saw vcc installing but not .net or directx. Is it because .net is already somehow built into proton? I feel like installing vcc and .net should pretty much be default for all of the games.

Again it is very easy and good GUI but I think my suggestions would make it better.


![IMG_20240403_162033](https://github.com/Gr3gorywolf/batocera_wine_manager/assets/45017079/5cdf588d-f0e3-421b-9f67-7b819cb6eef9)

**Comment by Gr3gorywolf** [comment]
thanks for your feedback, Honestly I didn't thought about a offline mode, but its a must, I gonna submit those changes In a future release, you'll see  a top banner to download the update once submitted, bout the redist install, the directx and vc are installed always but it happens without a UI interaction so that's why

**Comment by Gr3gorywolf** [comment]
@isilkin all done, open the app with internet and upgrade it, FYI the controller support is only available when you launch the app from ports section, otherwise you may have to use mouse and keyboard

**Comment by isilkin** [comment]
Hi, in the v40 Batocera has an option to pick a custom runner per game configuration. I still use your app a lot because it has the ability to install dependencies. Though, when I copy one of the protons from wine manager to system/wine/custom/ to use as a custom runner in Batocera the game does not lunch (the games lunch fine if I use your app to set default runner). What is the difference? Do I need to edit some file somewhere so Batocera allows me to use one of the downloaded runners?

**Comment by Gr3gorywolf** [comment]
Yeah, thats something that im currently dealing with, im figuring out a way to make it backwards compatible with v38, 39 and also allow the custom runners on v40,

**Comment by Gr3gorywolf** [comment]
@isilkin the fix is up, please if you have created a system/wine/custom folder please rename it back to protons then update the app and it will be automatically renamed to /wine/custom with all the protons patched to work with the runners, please read this section of the readme https://github.com/Gr3gorywolf/batocera_wine_manager?tab=readme-ov-file#compatibility it details everything about the new compatibility with v40

**Comment by isilkin** [comment]
I tested it on v40 and everything worked as intended. Good Job!

**Comment by Gr3gorywolf** [comment]
Nice to hear, If there's anything that goes wrong just let me know
